# Assignment 1

Predict the price of the Uber ride from a given pickup point to the agreed drop-off location.
Perform following tasks:
1. Pre-process the dataset.
2. Identify outliers.
3. Check the correlation.
4. Implement linear regression and random forest regression models.
5. Evaluate the models and compare their respective scores like R2, RMSE, etc.

Dataset link: https://www.kaggle.com/datasets/yasserh/uber-fares-dataset

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import os

In [ ]:
# print(os.getcwd())
df=pd.read_csv("ML/uber.csv")
df.head()

In [ ]:
# Drop the 3 columns that are not needed
df = df.drop(['Unnamed: 0','key','pickup_datetime'], axis=1)

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in <module>
NameError: name 'df' is not defined



In [ ]:
df.isnull().sum()

fare_amount          0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64


In [ ]:
df = df.dropna()
df.isnull().sum()

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'df' is not defined



In [ ]:
plt.figure(figsize=(10,6))
sns.boxplot(data=df)
plt.show()

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in <module>
NameError: name 'df' is not defined



In [ ]:
# remove outliers
for col in df.columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lb = Q1 - 1.5 * IQR
    ub = Q3 + 1.5 * IQR
    
    df = df[(df[col] >= lb) & (df[col] <= ub)]

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in <module>
NameError: name 'df' is not defined



In [ ]:
scaler = StandardScaler()
scaled_df = scaler.fit_transform(df)

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in <module>
NameError: name 'df' is not defined



In [ ]:
scaled_df

[[-0.2932847  -1.1178711  -0.67988539 -1.10660975 -1.33944605 -0.47502273]
 [-0.24166807 -0.77733472 -1.15915782 -0.81952246 -0.1218992  -0.47502273]
 [ 1.10036418 -1.44370658 -0.565552    1.10237707  0.88068643 -0.47502273]
 ...
 [-0.2932847  -0.17673965 -0.75165417 -1.53471183 -0.60271092 -0.47502273]
 [ 1.51329718 -0.94995784 -1.29035095 -0.13227415 -2.58814233 -0.47502273]
 [ 1.41006393 -0.15635196 -1.54470586 -0.2693492   0.70758523 -0.47502273]]


In [ ]:
sns.heatmap(data=df.corr(), annot=True)
plt.show()

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'df' is not defined



In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X = df[["pickup_longitude", "pickup_latitude", "dropoff_longitude", "dropoff_latitude", "passenger_count"]]
Y = df["fare_amount"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 5, in <module>
NameError: name 'df' is not defined



In [ ]:
model = LinearRegression()
model.fit(X_train, Y_train)

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in <module>
NameError: name 'X_train' is not defined



In [ ]:
y_pred = model.predict(X_test)

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'X_test' is not defined



In [ ]:
r2score = r2_score(Y_test,y_pred)
print("R2 Score: ", r2score)
rmse = np.sqrt(mean_squared_error(Y_test,y_pred))
print("RMSE: ",rmse)

R2 Score:  0.012407378715066364
RMSE:  3.849899653661398


## Random Forest Regression

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model1 = RandomForestRegressor()
model1.fit(X_train,Y_train)

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in <module>
NameError: name 'X_train' is not defined



In [ ]:
y_pred = model1.predict(X_test)
y_pred

Traceback (most recent call last):
  File "c:\Users\omani\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'X_test' is not defined



In [ ]:
r2score = r2_score(Y_test,y_pred)
print("R2 Score: ", r2score)
rmse = np.sqrt(mean_squared_error(Y_test,y_pred))
print("RMSE: ",rmse)

R2 Score:  0.7044146748768623
RMSE:  2.1030320430688336
